language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install pip --upgrade
  - pip install setuptools --upgrade
  - pip install -r requirements/dev.txt
script:
  - flake8 .
  - pytest
after_success:
  - coverage report -m
